version: "3"
services:
  redis:
    image: 'redis:latest'
  cpo-core:
    build:
      dockerfile: 'Dockerfile'
      context: .
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - DB_URI=${DB_URI}
      - EVENT_SIMULATOR_HOST=${EVENT_SIMULATOR_HOST}
      - GUPSHUP_APP_NAME=${GUPSHUP_APP_NAME}
      - GUPSHUP_API_KEY=${GUPSHUP_API_KEY}
      - GUPSHUP_HOST=${GUPSHUP_HOST}
      - REDIS_URL=redis://redis:6379
      - CAMUNDA_PASSWORD=${CAMUNDA_PASSWORD}
      - GUPSHUP_SOURCE_CONTACT=${GUPSHUP_SOURCE_CONTACT}
      - CALLBACK_HOST=${CALLBACK_HOST}
    ports:
      - '8080:8080'