# fly.toml file generated for cpo-core on 2023-04-16T06:58:27+05:30

app = "cpo-core"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
