spring.datasource.url: jdbc:h2:file:./camunda-h2-database
camunda.bpm.admin-user:
  id: demo
  password: demo
server:
  port: 8080
gupshup-host: "https://api.gupshup.io/"
gupshup-api-key: "zy34whfcvkisweigfskw4sskyxw9o7ld"
gupshup-app-name: "AtherSales2"
gupshup-source-contact: "917834811114"
cb-auth-key: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc19tYWNoaW5lIjp0cnVlLCJpYXQiOjE2NzgxMDY0ODl9.GPwlZdmg2fZm2ME22q54cNuz-PrPxMqVDhNR32A8VJk"
ny-backend-host: "https://ny-mock-api.fly.dev/api/v1"
spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: "cpo"
camunda.process-definition-id:
  booking-flow: Process_1bgrwav:8:312c6b52-d312-11ed-8bc5-f6a8ace2dc6a #id of the deployed BPMN process, every change in BPMN will lead to a new ID.
  ride-flow: Process_1hhq3j4:3:312c4441-d312-11ed-8bc5-f6a8ace2dc6a
  language-change-flow: Process_18f0e8v:1:b59820a5-d355-11ed-b6a1-76b3e82a2871
