spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring.redis.url: ${REDIS_URL}
camunda.bpm.admin-user:
  id: demo
  password: ${CAMUNDA_PASSWORD}
server:
  port: 8080
gupshup-host: ${GUPSHUP_HOST}
gupshup-api-key: ${GUPSHUP_API_KEY}
gupshup-app-name: ${GUPSHUP_APP_NAME}
gupshup-source-contact: ${GUPSHUP_SOURCE_CONTACT}
ny-backend-host: ${BACKEND_HOST}
callback-host: ${CALLBACK_HOST}
event-simulator-host: ${EVENT_SIMULATOR_HOST}
spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: "cpo"
camunda.process-definition-id:
  booking-flow: Process_1bgrwav:8:312c6b52-d312-11ed-8bc5-f6a8ace2dc6a #id of the deployed BPMN process, every change in BPMN will lead to a new ID.
  ride-flow: Process_1hhq3j4:3:312c4441-d312-11ed-8bc5-f6a8ace2dc6a
  language-change-flow: Process_18f0e8v:1:b59820a5-d355-11ed-b6a1-76b3e82a2871

#Camunda external service task client configuration
camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
  lock-duration: 10000
  subscriptions:
    fetchNearbyRides:
      variable-names: destination_latitude, destination_longitude, source_latitude, source_longitude, ride_selection_mode
      process-definition-key: Process_1bgrwav