spring.datasource.url: jdbc:h2:file:./camunda-h2-database
camunda.bpm.admin-user:
  id: cpo
  password: givemeaccess
server:
  port: 8080
ny-backend-host: "http://localhost:3001/api/v1"
spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: "cpo"