spring.datasource.url: jdbc:h2:file:./camunda-h2-database
camunda.bpm.admin-user:
  id: demo
  password: demo
server:
  port: 8080
ny-backend-host: "https://ny-mock-api.fly.dev/api/v1"
spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: "cpo"