# fly.toml file generated for ny-mock-api on 2023-04-02T22:44:37+05:30

app = "ny-mock-api"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "dfw"
processes = []

[[services]]
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
